### PR TITLE
csv handler

### PR DESCRIPTION
**Pull request by FeeeDz**
## Description
Svedberg_Ornithoscopy

### Change List
Please include a summary of the change and which issue is fixed. 

### Reasons for the PR
Please also include relevant motivation and context. 

### New Dependencies and Reason
List any dependencies that are required for this change and the reason for the dependency add.

## Issues List
Closes # (issue)

**Additional context**
Add any other context or information about the problem here.

**List of Developers**
This feature will be implemented by the following Developers:
- @GithubProfileTag

## Type of changes
Please check relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

> **NOTE**: the PR have to be labelled `in-progress` until the work is complete, the PR will be checked, reviewed and merged only after being labelled as `complete`

### CODE REVIEW

**Comment by FeeeDz** [comment]
il codice funziona correttamente sul mio pc (Linux) Python versione 3.10.6 ma a @FrancescoValentini  (su windows) concatenava la prima riga che andava ad inserire sulla riga dell'ultimo record presente.
Poichè a me funzionava correttamente non sono riuscito a fixare questo "bug(?)" che si verifica su windows.
Attendo riscontri ^.^

**Review by HarlockOfficial — COMMENTED** [review]
Pls check that the string added to the CSV file contains the standard newline characters "\r\n" for multi platform support.
The data might be put all in one line depending on the system

**Comment by FeeeDz** [comment]
provato su windows e linux ora worka

**Comment by FrancescoValentini** [comment]
L'inserimento funziona ma la rimozione di un record no.

**Comment by FeeeDz** [comment]
> L'inserimento funziona ma la rimozione di un record no.

Non capisco.. a me funziona. Se puoi allegare screen per confrontare i risultati o vedere direttamente se su linux ti worka, perchè così non riesco a capire dove sia il problema.

**Comment by FrancescoValentini** [comment]
Quando elimino un qualsiasi record questo è quello che succede al file 
image

**Comment by FeeeDz** [comment]
> Quando elimino un qualsiasi record questo è quello che succede al file image

non riesco a capire cosa sia successo perdonami ;/

**Comment by HarlockOfficial** [comment]
> 

I guess he refers to the new lines added to the file.

I think the file looked something like:
Line;one;content;foo
Line;two;content;bar
Line;three;content;test

And now looks like:
Line;one;content;foo

Line;two;content;bar

Line;three;content;test

(With the extra new lines)

**Comment by dmitry-mingazov** [comment]
Confermo che funziona su Linux (Ubuntu 22.04) usando Python3.9. Provato sia con un file che usa \n, sia con un file che usa \r\n.

**Pull request merged**
